# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import admin_pb2 as admin__pb2


class AdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/admin.AdminService/List',
                request_serializer=admin__pb2.AdminListRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminListResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/admin.AdminService/Get',
                request_serializer=admin__pb2.AdminRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminResponse.FromString,
                )
        self.Create = channel.unary_unary(
                '/admin.AdminService/Create',
                request_serializer=admin__pb2.AdminCreateRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/admin.AdminService/Update',
                request_serializer=admin__pb2.AdminUpdateRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/admin.AdminService/Delete',
                request_serializer=admin__pb2.AdminDeleteRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminDeleteResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/admin.AdminService/Login',
                request_serializer=admin__pb2.AdminLoginRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminLoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/admin.AdminService/Logout',
                request_serializer=admin__pb2.AdminLogoutRequest.SerializeToString,
                response_deserializer=admin__pb2.AdminLogoutResponse.FromString,
                )


class AdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=admin__pb2.AdminListRequest.FromString,
                    response_serializer=admin__pb2.AdminListResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=admin__pb2.AdminRequest.FromString,
                    response_serializer=admin__pb2.AdminResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=admin__pb2.AdminCreateRequest.FromString,
                    response_serializer=admin__pb2.AdminResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=admin__pb2.AdminUpdateRequest.FromString,
                    response_serializer=admin__pb2.AdminResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=admin__pb2.AdminDeleteRequest.FromString,
                    response_serializer=admin__pb2.AdminDeleteResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=admin__pb2.AdminLoginRequest.FromString,
                    response_serializer=admin__pb2.AdminLoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=admin__pb2.AdminLogoutRequest.FromString,
                    response_serializer=admin__pb2.AdminLogoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'admin.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/List',
            admin__pb2.AdminListRequest.SerializeToString,
            admin__pb2.AdminListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Get',
            admin__pb2.AdminRequest.SerializeToString,
            admin__pb2.AdminResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Create',
            admin__pb2.AdminCreateRequest.SerializeToString,
            admin__pb2.AdminResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Update',
            admin__pb2.AdminUpdateRequest.SerializeToString,
            admin__pb2.AdminResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Delete',
            admin__pb2.AdminDeleteRequest.SerializeToString,
            admin__pb2.AdminDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Login',
            admin__pb2.AdminLoginRequest.SerializeToString,
            admin__pb2.AdminLoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/admin.AdminService/Logout',
            admin__pb2.AdminLogoutRequest.SerializeToString,
            admin__pb2.AdminLogoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
