# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: penjadwalan.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11penjadwalan.proto\x12\x0bpenjadwalan\"\xc1\x01\n\x06Jadwal\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08instansi\x18\x02 \x01(\t\x12\x0e\n\x06\x61lamat\x18\x03 \x01(\t\x12\x0f\n\x07tanggal\x18\x04 \x01(\t\x12\x12\n\npetugas_id\x18\x05 \x03(\t\x12\x18\n\x10penanggung_jawab\x18\x06 \x01(\t\x12\x1f\n\x17kontak_penanggung_jawab\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\x05\x12\x19\n\x11jenis_sampling_id\x18\t \x01(\t\"H\n\x12JadwalListResponse\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.penjadwalan.Jadwal\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x13\n\x11JadwalListRequest\"D\n\x0eJadwalResponse\x12!\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x13.penjadwalan.Jadwal\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1b\n\rJadwalRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\xc2\x01\n\x13\x43reateJadwalRequest\x12\x10\n\x08instansi\x18\x01 \x01(\t\x12\x0e\n\x06\x61lamat\x18\x02 \x01(\t\x12\x0f\n\x07tanggal\x18\x03 \x01(\t\x12\x12\n\npetugas_id\x18\x04 \x03(\t\x12\x18\n\x10penanggung_jawab\x18\x05 \x01(\t\x12\x1f\n\x17kontak_penanggung_jawab\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\x05\x12\x19\n\x11jenis_sampling_id\x18\x08 \x01(\t\"\'\n\x14\x44\x65leteJadwalResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x13\x44\x65leteJadwalRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xd3\x02\n\rJadwalService\x12R\n\rGetJadwalList\x12\x1e.penjadwalan.JadwalListRequest\x1a\x1f.penjadwalan.JadwalListResponse\"\x00\x12\x46\n\tGetJadwal\x12\x1a.penjadwalan.JadwalRequest\x1a\x1b.penjadwalan.JadwalResponse\"\x00\x12O\n\x0c\x43reateJadwal\x12 .penjadwalan.CreateJadwalRequest\x1a\x1b.penjadwalan.JadwalResponse\"\x00\x12U\n\x0c\x44\x65leteJadwal\x12 .penjadwalan.DeleteJadwalRequest\x1a!.penjadwalan.DeleteJadwalResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'penjadwalan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JADWAL']._serialized_start=35
  _globals['_JADWAL']._serialized_end=228
  _globals['_JADWALLISTRESPONSE']._serialized_start=230
  _globals['_JADWALLISTRESPONSE']._serialized_end=302
  _globals['_JADWALLISTREQUEST']._serialized_start=304
  _globals['_JADWALLISTREQUEST']._serialized_end=323
  _globals['_JADWALRESPONSE']._serialized_start=325
  _globals['_JADWALRESPONSE']._serialized_end=393
  _globals['_JADWALREQUEST']._serialized_start=395
  _globals['_JADWALREQUEST']._serialized_end=422
  _globals['_CREATEJADWALREQUEST']._serialized_start=425
  _globals['_CREATEJADWALREQUEST']._serialized_end=619
  _globals['_DELETEJADWALRESPONSE']._serialized_start=621
  _globals['_DELETEJADWALRESPONSE']._serialized_end=660
  _globals['_DELETEJADWALREQUEST']._serialized_start=662
  _globals['_DELETEJADWALREQUEST']._serialized_end=695
  _globals['_JADWALSERVICE']._serialized_start=698
  _globals['_JADWALSERVICE']._serialized_end=1037
# @@protoc_insertion_point(module_scope)
