# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import petugas_pb2 as petugas__pb2


class PetugasServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePetugas = channel.unary_unary(
                '/petugas.PetugasService/CreatePetugas',
                request_serializer=petugas__pb2.CreatePetugasRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasResponse.FromString,
                )
        self.PetugasList = channel.unary_unary(
                '/petugas.PetugasService/PetugasList',
                request_serializer=petugas__pb2.PetugasListRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasListResponse.FromString,
                )
        self.Petugas = channel.unary_unary(
                '/petugas.PetugasService/Petugas',
                request_serializer=petugas__pb2.PetugasRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasResponse.FromString,
                )
        self.UpdatePetugas = channel.unary_unary(
                '/petugas.PetugasService/UpdatePetugas',
                request_serializer=petugas__pb2.UpdatePetugasRequest.SerializeToString,
                response_deserializer=petugas__pb2.PetugasResponse.FromString,
                )
        self.DeletePetugas = channel.unary_unary(
                '/petugas.PetugasService/DeletePetugas',
                request_serializer=petugas__pb2.DeletePetugasRequest.SerializeToString,
                response_deserializer=petugas__pb2.DeletePetugasResponse.FromString,
                )
        self.LoginPetugas = channel.unary_unary(
                '/petugas.PetugasService/LoginPetugas',
                request_serializer=petugas__pb2.LoginPetugasRequest.SerializeToString,
                response_deserializer=petugas__pb2.LoginPetugasResponse.FromString,
                )


class PetugasServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePetugas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PetugasList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Petugas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePetugas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePetugas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginPetugas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PetugasServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePetugas': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePetugas,
                    request_deserializer=petugas__pb2.CreatePetugasRequest.FromString,
                    response_serializer=petugas__pb2.PetugasResponse.SerializeToString,
            ),
            'PetugasList': grpc.unary_unary_rpc_method_handler(
                    servicer.PetugasList,
                    request_deserializer=petugas__pb2.PetugasListRequest.FromString,
                    response_serializer=petugas__pb2.PetugasListResponse.SerializeToString,
            ),
            'Petugas': grpc.unary_unary_rpc_method_handler(
                    servicer.Petugas,
                    request_deserializer=petugas__pb2.PetugasRequest.FromString,
                    response_serializer=petugas__pb2.PetugasResponse.SerializeToString,
            ),
            'UpdatePetugas': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePetugas,
                    request_deserializer=petugas__pb2.UpdatePetugasRequest.FromString,
                    response_serializer=petugas__pb2.PetugasResponse.SerializeToString,
            ),
            'DeletePetugas': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePetugas,
                    request_deserializer=petugas__pb2.DeletePetugasRequest.FromString,
                    response_serializer=petugas__pb2.DeletePetugasResponse.SerializeToString,
            ),
            'LoginPetugas': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginPetugas,
                    request_deserializer=petugas__pb2.LoginPetugasRequest.FromString,
                    response_serializer=petugas__pb2.LoginPetugasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'petugas.PetugasService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PetugasService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePetugas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/CreatePetugas',
            petugas__pb2.CreatePetugasRequest.SerializeToString,
            petugas__pb2.PetugasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PetugasList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/PetugasList',
            petugas__pb2.PetugasListRequest.SerializeToString,
            petugas__pb2.PetugasListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Petugas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/Petugas',
            petugas__pb2.PetugasRequest.SerializeToString,
            petugas__pb2.PetugasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePetugas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/UpdatePetugas',
            petugas__pb2.UpdatePetugasRequest.SerializeToString,
            petugas__pb2.PetugasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePetugas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/DeletePetugas',
            petugas__pb2.DeletePetugasRequest.SerializeToString,
            petugas__pb2.DeletePetugasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginPetugas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/petugas.PetugasService/LoginPetugas',
            petugas__pb2.LoginPetugasRequest.SerializeToString,
            petugas__pb2.LoginPetugasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
